"""empty message

Revision ID: 68dbed5c8f77
Revises: 44c2e09794d0
Create Date: 2026-06-11 14:10:49.338715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dbed5c8f77'
down_revision = '44c2e09794d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('csv_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('full_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('work_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('error_message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('work_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('full_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.alter_column('csv_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
