"""empty message

Revision ID: a2db09698d11
Revises: 68dbed5c8f77
Create Date: 2026-06-11 17:21:28.011932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2db09698d11'
down_revision = '68dbed5c8f77'
branch_labels = None
depends_on = None

job_status_enum = sa.Enum(
    'queued', 'processing', 'completed', 'failed',
    name='job_status_enum'
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    job_status_enum.create(bind, checkfirst=True)

    with op.batch_alter_table('analysis_jobs') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=job_status_enum,
            existing_nullable=False,
            postgresql_using="status::text::job_status_enum"
        )

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('files_job_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jobs') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=job_status_enum,
            existing_nullable=False,
            postgresql_using="status::text::job_status_enum"
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('queued', 'processing', 'completed', 'failed', name='job_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('files_job_id_fkey'), 'jobs', ['job_id'], ['id'])

    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('queued', 'processing', 'completed', 'failed', name='job_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    job_status_enum.drop(bind, checkfirst=True)

    # ### end Alembic commands ###
